import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getFirestore, collection, doc, getDocs, setDoc, writeBatch } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { getStorage, ref, uploadString, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js";
const cfg={apiKey:"AIzaSyAyUMzv-Zw_XtNe4OKJPg2FrwyLSJh5i9A",authDomain:"al-tariq-media.firebaseapp.com",projectId:"al-tariq-media",storageBucket:"al-tariq-media.firebasestorage.app",messagingSenderId:"616239800441",appId:"1:616239800441:web:53edc96e1cc872702cb4a8"};
const app=getApps().length?getApps()[0]:initializeApp(cfg), db=getFirestore(app), storage=getStorage(app);
const SETTINGS_KEY='altariq_media_website_settings_v1', DB_NAME='altariq_media_admin_database_v2', STORE='projects';
function readSettings(){try{return JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}catch{return {}}}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})}})}
async function readProjects(){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readonly'),r=t.objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
const urlCache=new Map();
async function publicProject(p){let publicImage=p.image||'';if(/^data:image\//i.test(publicImage)){const sig=`${p.id}:${p.updated||''}:${publicImage.length}`;if(urlCache.has(sig)) publicImage=urlCache.get(sig); else {const r=ref(storage,`website/projects/${p.id}.jpg`);await uploadString(r,publicImage,'data_url');publicImage=await getDownloadURL(r);urlCache.set(sig,publicImage)}}return {...p,publicImage,image:publicImage}}
let busy=false,last='';
async function syncAll(){if(busy)return;busy=true;try{const settings=readSettings(),projects=await readProjects();const signature=JSON.stringify([settings.savedAt,projects.map(p=>[p.id,p.updated,p.status,p.name,p.driveLink,p.image?.length])]);if(signature===last)return;await setDoc(doc(db,'website_config','main'),{...settings,syncedAt:new Date().toISOString()},{merge:false});const existing=await getDocs(collection(db,'')),ids=new Set(projects.map(p=>String(p.id))),batch=writeBatch(db);existing.forEach(d=>{if(!ids.has(d.id))batch.delete(d.ref)});for(const p of projects){const id=String(p.id||crypto.randomUUID()),pub=await publicProject({...p,id});batch.set(doc(db,'',id),pub,{merge:false})}await batch.commit();last=signature;console.info('Public website synced from admin.')}catch(e){console.warn('Public sync failed. Check Firestore/Storage rules.',e)}finally{busy=false}}
window.addEventListener('altariq:website-settings-updated',syncAll);window.addEventListener('storage',e=>{if(e.key===SETTINGS_KEY)syncAll()});setInterval(syncAll,1800);setTimeout(syncAll,700);
